//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracivnyk
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Poz { get; set; }
        public Nullable<int> ZP { get; set; }
        public string Stavka { get; set; }
        public byte[] Image { get; set; }
    }
}
